# Generated by Django 3.2.12 on 2024-07-19 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
